// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using espaco_seguro_api._4___Data;

#nullable disable

namespace espaco_seguro_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102070617_corrige-tipo-coluna-data_nascimento")]
    partial class corrigetipocolunadata_nascimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.CertificacaoMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_validadade");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medico_id");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("StatusCertificacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TipoCertificado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_certificacao");

                    b.Property<string>("UrlDocumento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_certificado");

                    b.Property<Guid>("medico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("medico_id");

                    b.ToTable("certificacao_medico", t =>
                        {
                            t.Property("medico_id")
                                .HasColumnName("medico_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.ComentarioPostagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Anonimo")
                        .HasColumnType("boolean")
                        .HasColumnName("anonimo");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<int>("ContagemCurtidas")
                        .HasColumnType("integer")
                        .HasColumnName("contagem_curtidas");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<Guid>("PostagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("postagem_id");

                    b.Property<string>("StatusComentarioPostagem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("autor_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("postagem_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("autor_id");

                    b.HasIndex("postagem_id");

                    b.ToTable("comentario_postagem", t =>
                        {
                            t.Property("autor_id")
                                .HasColumnName("autor_id1");

                            t.Property("postagem_id")
                                .HasColumnName("postagem_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.ConteudoCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resumo");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlMidia")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url_midia");

                    b.Property<Guid>("autor_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("autor_id");

                    b.ToTable("conteudo_card", t =>
                        {
                            t.Property("autor_id")
                                .HasColumnName("autor_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.FonteCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<bool>("FontePrimaria")
                        .HasColumnType("boolean")
                        .HasColumnName("fonte_primaria");

                    b.Property<string>("Publicador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("publicador");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.Property<Guid>("cartao_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("cartao_id");

                    b.ToTable("fonte_card", t =>
                        {
                            t.Property("cartao_id")
                                .HasColumnName("cartao_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("crm");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<DateTime?>("DataVerificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_verificacao");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("especialidade");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacoes");

                    b.Property<string>("StatusMedico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_verificacao");

                    b.Property<string>("UfCrm")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf_crm");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("VerificadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("verificado_por");

                    b.Property<Guid>("usuario_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("usuario_id")
                        .IsUnique();

                    b.ToTable("medico", t =>
                        {
                            t.Property("usuario_id")
                                .HasColumnName("usuario_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.MensagemChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio");

                    b.Property<DateTime?>("DataLida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lida");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean")
                        .HasColumnName("lida");

                    b.Property<Guid?>("RemetenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("remetente_id");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_id");

                    b.Property<string>("TipoMensagem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_mensagem");

                    b.Property<Guid>("remetente_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("sessao_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("remetente_id");

                    b.HasIndex("sessao_id");

                    b.ToTable("mensagem_chat", t =>
                        {
                            t.Property("remetente_id")
                                .HasColumnName("remetente_id1");

                            t.Property("sessao_id")
                                .HasColumnName("sessao_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Postagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Anonimo")
                        .HasColumnType("boolean")
                        .HasColumnName("anonimo");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<int>("ContagemComentarios")
                        .HasColumnType("integer")
                        .HasColumnName("contagem_comentarios");

                    b.Property<int>("ContagemCurtidas")
                        .HasColumnType("integer")
                        .HasColumnName("contagem_curtidas");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao");

                    b.Property<string>("StatusPostagem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("autor_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("autor_id");

                    b.ToTable("postagem", t =>
                        {
                            t.Property("autor_id")
                                .HasColumnName("autor_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.SessaoChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Anonima")
                        .HasColumnType("boolean")
                        .HasColumnName("anonima");

                    b.Property<DateTime?>("EncerradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("StatusChat")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TipoChat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_chat");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("usuario_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("usuario_id");

                    b.ToTable("sessao_chat", t =>
                        {
                            t.Property("usuario_id")
                                .HasColumnName("usuario_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AceitouTermos")
                        .HasColumnType("boolean")
                        .HasColumnName("aceitou_termos");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime?>("DataAceiteTermos")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aceite_termos");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("funcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("StatusUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso");

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.VerificacaoCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AfirmacoesConferidas")
                        .HasColumnType("boolean")
                        .HasColumnName("afirmacoes_conferidas");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cartao_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<bool>("FontePrimariaOk")
                        .HasColumnType("boolean")
                        .HasColumnName("fonte_primaria_ok");

                    b.Property<bool>("LinguagemAcessivel")
                        .HasColumnType("boolean")
                        .HasColumnName("linguagem_acessivel");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("curador_id");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<bool>("SemAlarmismo")
                        .HasColumnType("boolean")
                        .HasColumnName("sem_alarmismo");

                    b.Property<bool>("SemPrescricaoMedica")
                        .HasColumnType("boolean")
                        .HasColumnName("sem_prescricao_medica");

                    b.Property<string>("StatusVerificacaoCard")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_verificacao_card");

                    b.Property<DateTime>("VerificadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_verificacao");

                    b.Property<Guid>("cartao_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("medico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("cartao_id");

                    b.HasIndex("medico_id");

                    b.ToTable("verificacao_card", t =>
                        {
                            t.Property("cartao_id")
                                .HasColumnName("cartao_id1");
                        });
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.CertificacaoMedico", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Medico", "Medico")
                        .WithMany("Certificacoes")
                        .HasForeignKey("medico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.ComentarioPostagem", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("autor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Postagem", "Postagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("postagem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.ConteudoCard", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Usuario", "Autor")
                        .WithMany("Cartoes")
                        .HasForeignKey("autor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.FonteCard", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.ConteudoCard", "Cartao")
                        .WithMany("Fonte")
                        .HasForeignKey("cartao_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Medico", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Usuario", "Usuario")
                        .WithOne("Medico")
                        .HasForeignKey("espaco_seguro_api._3___Domain.Entities.Medico", "usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.MensagemChat", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("remetente_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("espaco_seguro_api._3___Domain.Entities.SessaoChat", "Sessao")
                        .WithMany("Mensagens")
                        .HasForeignKey("sessao_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Remetente");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Postagem", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Usuario", "Autor")
                        .WithMany("Postagens")
                        .HasForeignKey("autor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.SessaoChat", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sessoes")
                        .HasForeignKey("usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.VerificacaoCard", b =>
                {
                    b.HasOne("espaco_seguro_api._3___Domain.Entities.ConteudoCard", "Cartao")
                        .WithMany("Verificacao")
                        .HasForeignKey("cartao_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("espaco_seguro_api._3___Domain.Entities.Usuario", "Medico")
                        .WithMany()
                        .HasForeignKey("medico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.ConteudoCard", b =>
                {
                    b.Navigation("Fonte");

                    b.Navigation("Verificacao");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Medico", b =>
                {
                    b.Navigation("Certificacoes");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Postagem", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.SessaoChat", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("espaco_seguro_api._3___Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("Medico");

                    b.Navigation("Postagens");

                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
